name: base_api_client
description: Base API Client to handle API calling and errors easily with loading.
version: 0.0.2
homepage: https://github.com/swarupbhanjachowdhury/base_api_client
author: Swarup Bhanja Chowdhury <swarupbhanjachowdhury@gmail.com>
repository: https://github.com/swarupbhanjachowdhury/base_api_client


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  get: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700